version: '3'
services:
  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db

  backend:
    container_name: backend
    build: ./backend
    image: mvictorn/yolo-backend:v1.0.0
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    environment:
      - DATABASE_URL=mongodb://mongodb:27017
    stdin_open: true
    tty: true

  frontend:
    build: ./client
    image: mvictorn/yolo-frontend:v1.0.4
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
    depends_on:
      - backend
    stdin_open: true
    tty: true

networks:
  default:

volumes:
  mongodb_data:
