version: '3'
services:
  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db

  backend:
    container_name: backend
    build: ./backend
    ports:
      - 5010:5000
    depends_on:
      - mongodb
    environment:
      - DATABASE_URL=mongodb://mongodb:27017
    stdin_open: true
    tty: true

  frontend:
    build: ./client
    container_name: yolo-frontend
    ports:
      - "8000:3000"
    volumes:
      - ./client:/client
    stdin_open: true
    tty: true

volumes:
  mongodb_data:
